# Generated by Django 4.0.5 on 2022-06-27 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Architecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='URL')),
                ('name', models.CharField(max_length=16)),
                ('describe', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Cathegory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='URL')),
                ('name', models.CharField(max_length=128)),
                ('describe', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Proccessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='URL')),
                ('name', models.CharField(max_length=128)),
                ('describe', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('architect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.architecture')),
            ],
        ),
        migrations.CreateModel(
            name='ECT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='URL')),
                ('name', models.CharField(max_length=256)),
                ('describe', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('cathegory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.cathegory')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.proccessor')),
            ],
        ),
    ]
