# Generated by Django 4.0.5 on 2022-06-22 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_etc_ect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cathegory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('describe', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.AddField(
            model_name='ect',
            name='cathegory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.cathegory'),
        ),
    ]
